# Generated by Django 5.2.3 on 2025-06-12 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_applications', models.CharField(max_length=100)),
                ('logo_applications', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Serveurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateurs', models.CharField(max_length=100)),
                ('prenom_utilisateurs', models.CharField(max_length=100)),
                ('email_utilisateurs', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_services', models.CharField(max_length=100)),
                ('date_lancement', models.DateField()),
                ('espace_memoire_utilise', models.IntegerField(help_text='en Mo')),
                ('memoire_vive_necessaire', models.IntegerField(help_text='en Mo')),
                ('serveur_lancement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.serveurs')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ressource', models.CharField(choices=[('Web', 'Web'), ('DB', 'Base de données'), ('Stockage', 'Stockage')], max_length=50)),
                ('applications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.applications')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.services')),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='utilisateur_applications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.utilisateurs'),
        ),
    ]
