# Generated by Django 5.2.3 on 2025-06-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeServeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description_serveurs', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='serveurs',
            name='nom',
        ),
        migrations.AddField(
            model_name='serveurs',
            name='capacite_memoire_serveurs',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='serveurs',
            name='capacite_stockage_serveurs',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='serveurs',
            name='nom_serveurs',
            field=models.CharField(default='serveur_test', max_length=100),
        ),
        migrations.AddField(
            model_name='serveurs',
            name='nombre_processeur_serveurs',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='serveurs',
            name='type_serveur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='monapp.typeserveurs'),
        ),
    ]
