# Generated by Django 5.2.3 on 2025-06-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_typeserveurs_remove_serveurs_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='cpu_utilise',
            field=models.IntegerField(default=1, help_text='Nombre de CPU nécessaires'),
        ),
        migrations.AddField(
            model_name='applications',
            name='memoire_utilisee',
            field=models.IntegerField(default=0, help_text='Mémoire utilisée en Mo'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='logo_applications',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
